version: '3.8'

services:
  rubberduck:
    image: python:3.11-slim
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt &&
             python main.py"
    environment:
      - PYTHONPATH=/app